### ISSUE TITLE
Run a single test in IntelliJ

### ISSUE THREAD

**Issue by privetr** [google/TestParameterInjector#6]
Hi, 
Thank you for this nice runner, 
I wanted to know if it is possible to run a test unitary without running whole test class each time ? 
Because if I run only 1 test, i encounter the following error : 
java.lang.Exception: No tests found matching Method...

Thank you for your reply,
Feel free to close the issue if it will never be possible

**Comment by nymanjens** [comment]
Hi,

What tool are you using to run the single test?

**Comment by privetr** [comment]
I run it with the Android Studio option on each test for a kotlin app.

**Comment by nymanjens** [comment]
Correct me if I'm wrong, but Android Studio is backed by IntelliJ, right?

If so, this is a feature request that is on our radar. After some initial analysis, we believe the best fix for this is to update the [IntelliJ JUnit4TestRunnerUtil.java](https://github.com/JetBrains/intellij-community/blob/6a1257e1a2e843058a3a49578d5c843ecafca0c6/plugins/junit_rt/src/com/intellij/junit4/JUnit4TestRunnerUtil.java).

**Comment by ibado-eb** [comment]
Hi, my team and I are really interested on using this library! 
Would be great to have the ability to run tests individually. 
Please let me know if we can help

**Comment by nymanjens** [comment]
@alexjski was working on this last we spoke

**Comment by alexjski** [comment]
I sent a [PR](https://github.com/JetBrains/intellij-community/pull/1556) for Intellij which addresses the issue. The problem with that if it is merged, my understanding is that it will be made available in next intellij release, so until then (and users picking up the new version) the problem remains.

We could also apply a workaround on our side, however it is not possible to have parameter values filtered correctly with that. In fact, I believe such workaround would make it at least more complicated to reconcile with a proper fix on the IDE side. My preference would be to try to get the fix in for Intellij and just encourage users to update -- please let me know if that is not an acceptable solution.

**Comment by ibado-eb** [comment]
Hi @alexjski, if by ` is not possible to have parameter values filtered correctly` you mean the individual test will run as many times as parameter values has, that would be totally ok for me 👍  Waiting for JetBrains + Android Studio to integrate the fix is gonna take a while.. Anyway, thanks for your help! Appreciate it

**Comment by ultraon** [comment]
I use a temporary workaround for that:
as soon as someone wants to run a test method individually from AndroidStudio (IntelliJ IDEA) just comment out the line with `@RunWith(TestParameterInjector::class)` and use only test class properties (not test method parameters) with annotation `@TestParameter` and a default value for it.
;-)
You can put a comment about that restriction/workaround above the test class to help your colleagues with the approach.

**Comment by alexjski** [comment]
> Hi @alexjski, if by ` is not possible to have parameter values filtered correctly` you mean the individual test will run as many times as parameter values has, that would be totally ok for me  Waiting for JetBrains + Android Studio to integrate the fix is gonna take a while.. Anyway, thanks for your help! Appreciate it

The problem we are facing is that the test runner in Intellij creates an opaque `Filter` which does not include the information about the parameter value, hence without the information, the best we can do is to run all combinations. I agree this is not the end of the world, but I wanted to test the ground about just getting that done in Intellij rather than adding a workaround internally and later deal with removing it.

The workaround is obvious -- run all combinations (in fact, I have a change lying around doing that exactly). The problem with it is that once Intellij does the right thing, then the workaround may hurt the usability and should eventually be removed (when?). This is why not creating a workaround internally is so tempting -- I hope that makes sense to you. I don't know if and when the PR for Intellij will be submitted and released -- if that was to happen soon, I would actually opt to say "please update your IDE". If it is the opposite/a lot of users must use older Intellij for a foreseeable future, that definitely changes the equation.

I think what I am hearing is that I should try a little harder (I may need to sacrifice some edge cases) to get the fix out quicker.

**Comment by nymanjens** [comment]
[According to IntelliJ](https://github.com/JetBrains/intellij-community/pull/1646#issuecomment-889741332), this should be fixed in their next release (2021.3)

**Comment by alexjski** [comment]
> According to IntelliJ, this should be fixed in their next release (2021.3)

I tested that at head and the problem still prevails. Filed https://youtrack.jetbrains.com/issue/IDEA-275586 for it.

**Comment by alexjski** [comment]
https://youtrack.jetbrains.com/issue/IDEA-275586 is [fixed](https://github.com/JetBrains/intellij-community/commit/fc1aaf271ef7c2033acea689b016ccaa0c83c95c) in 213.2441 build. I also validated the version at head does not suffer from the problem anymore.

Thank you, @akozlova for fixing that!
